from pathlib import Path
from xml.sax.saxutils import escape
import csv, json
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, PageBreak
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'output/pdf'; OUT.mkdir(parents=True,exist_ok=True)
FIG=ROOT/'results/figures'; FIG.mkdir(parents=True,exist_ok=True)
NAVY=colors.HexColor('#132D46'); TEAL=colors.HexColor('#087E8B'); GREY=colors.HexColor('#526579')
styles=getSampleStyleSheet()
for name,size,lead,bold,color in [('TitleX',27,32,True,NAVY),('H1X',18,23,True,NAVY),('H2X',11.5,16,True,TEAL),('BodyX',10,14.5,False,NAVY),('SmallX',8.3,11.3,False,GREY),('CellX',8.5,11.5,False,NAVY),('HeadX',8.5,11.5,True,colors.white)]:
    styles.add(ParagraphStyle(name=name,fontName='Helvetica-Bold' if bold else 'Helvetica',fontSize=size,leading=lead,textColor=color,spaceAfter=9 if name!='CellX' else 0))
def p(text,style='BodyX'): return Paragraph(text,styles[style])
def h(text): return p(text,'H1X')
def sub(text):return p(text,'H2X')
def table(rows,widths):
    t=Table([[p(escape(str(c)),'HeadX' if i==0 else 'CellX') for c in row] for i,row in enumerate(rows)],colWidths=widths,hAlign='LEFT',repeatRows=1)
    t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),NAVY),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.HexColor('#F0F5F8'),colors.white]),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),7),('RIGHTPADDING',(0,0),(-1,-1),7),('TOPPADDING',(0,0),(-1,-1),6),('BOTTOMPADDING',(0,0),(-1,-1),6),('LINEBELOW',(0,-1),(-1,-1),.5,colors.HexColor('#CBD6DE'))]));t.spaceAfter=10;return t
def image(name,width=491):
    im=Image(str(FIG/name));ratio=im.imageHeight/im.imageWidth; im.drawWidth=width; im.drawHeight=width*ratio;return im
def link(url,title):return f'<link href="{escape(url)}" color="#087E8B">{escape(title)}</link>'

def main():
    cap=list(csv.DictReader((ROOT/'results/CALENDAR_CAPACITY.csv').open(encoding='utf-8')))
    by={x['candidate']:x for x in cap}
    sources=json.loads((ROOT/'evidence/SOURCES.json').read_text())
    integrity=json.loads((ROOT/'results/INTEGRITY.json').read_text())
    metadata=json.loads((ROOT/'results/METADATA_REQUESTS.json').read_text())
    keys=['LSEG archive envelope','Tickdatamarket XAU quote listing','Original Design Pack window','Dukascopy minute metadata','HistData catalog envelope']
    labels=['1996 archive envelope*','Aug 1998 spot listing*','1999 design window','May 2003 minute start','2009 catalog year']
    values=[int(by[k]['loose_scored_ceiling_reserve_400']) for k in keys]
    fig,ax=plt.subplots(figsize=(9,3.4))
    ax.barh(labels,values,color=['#526579','#526579','#526579','#087E8B','#087E8B'],height=.62)
    ax.axvline(4000,color='#132D46',linestyle='--',linewidth=1.5,label='Required 4,000 scores')
    for y,v in enumerate(values):ax.text(v+35,y,f'{v:,}',va='center',fontsize=9,color='#132D46')
    ax.invert_yaxis();ax.set_xlim(0,5400);ax.set_xlabel('Optimistic scored-date ceiling: weekdays minus 400 training dates')
    ax.set_ylabel('History start assumption');ax.set_title('Calendar room before 2016, not observed coverage',loc='left',fontsize=12)
    ax.spines[['top','right']].set_visible(False);ax.legend(loc='lower right',frameon=False,fontsize=8);fig.tight_layout();fig.savefig(FIG/'calendar_capacity.png',dpi=180);plt.close(fig)
    story=[Spacer(1,15),p('Historical gold sources:<br/>can fresh history support<br/>the confirmation design?','TitleX'),p('Route A source feasibility audit | 06 October 2026','H2X'),p('Asian-session information and subsequent London realised variance in XAU/USD. A documentation and availability-metadata phase following Study III-C.'),Spacer(1,6),sub('Decision'),p('<b>No accessible qualifying source has been verified.</b> The search identifies three commercial spot-data candidates: Olsen, LSEG Tick History and Tickdatamarket. Their published evidence is promising but does not establish enough complete, usable daily sessions. The targeted search does not prove that no suitable dataset exists.'),table([['Finding','Implication'],['OANDA: at most 1,975 scores','Existing III-C timestamp/coverage audit fails the 4,000-date gate.'],['Dukascopy and HistData','Official advertised/listed intraday starts are too recent for this design.'],['Olsen / LSEG / Tickdatamarket','Obtain dated, instrument-specific quote inventories and access terms.'],['Long gold-futures archives','Different market and quote/trade definitions; no silent spot substitution.']],[154,337]),sub('What this phase establishes'),p('A source shortlist, reproducible calendar screens, four direct metadata/catalog request records and a provider questionnaire. No new market-price dataset was acquired. Quarantined OANDA prices were not opened numerically. Fresh RV, forecast losses and trading strategies were not evaluated; the 2024+ holdout remains closed.'),p('Studies I, II, the original Study III Design Pack, III-B and III-C retain their frozen files and conclusions. Their scope and acceptance gates are not amended by this audit.','SmallX'),PageBreak()]

    story += [h('1. Capacity is about unique dates'),p('The target is 4,000 scored daily forecasts, plus 400 initial eligible training dates and enough preceding observations to form the HAR features. More brokers, contracts or bar observations on one market date do not create additional independent daily forecasts.'),image('calendar_capacity.png'),p('Source: actual Monday-Friday calendar dates through 31 December 2015, combined with published start assumptions in S02-S05. *LSEG is an archive-wide envelope, not verified gold history; Tickdatamarket is a catalog claim. Holidays and quality exclusions are omitted.','SmallX'),table([['Start assumption','Weekdays W','W - 400','W - 420'],*[[by[k]['start_assumption'],by[k]['calendar_weekdays'],by[k]['loose_scored_ceiling_reserve_400'],by[k]['ideal_screen_reserve_20_features_and_400_training']] for k in keys]],[155,112,112,112]),p('<b>W - 400</b> is a loose upper bound after training. <b>W - 420</b> is an ideal screen allowing 20 initial feature dates when no earlier feature history is supplied. Neither is an observed eligible sample size. Actual eligibility also depends on session and daily coverage, quality, positive RV and feature continuity.'),p('The original 1999-2015 window has only 15 dates of margin after this ideal allowance. August 1998 has 124. The latter requires approximately 97.3% of all weekdays to supply feature/training/scored capacity even before accounting for how exclusions affect neighbouring feature eligibility. A start date on its own is insufficient.'),p('Using history earlier than 1999 would extend the original Design Pack period and must be declared in a separate source-specific registration. No such extension has been executed here.','SmallX'),PageBreak()]

    story += [h('2. Three spot-data candidates'),sub('Olsen: strongest evidence that older gold data existed [S01]'),p('A provider-hosted primary research book reports intraday XAU/USD analysis for January 1987-December 1995, with quote-activity analysis in 1987-1993. Its current historical product page offers quote data and regular-interval bars. This makes Olsen a serious documentary lead for earlier spot history.'),p('It does not verify current licensability, continuity through 2015 or complete Tokyo/London sessions. Request the original two-sided quote inventory, contributor provenance, timestamp rules and a single-instrument research quote. Published studies demonstrate historical existence; they are not a usable dataset delivery.'),sub('LSEG Tick History: plausible archive envelope [S02]'),p('LSEG states that its Level 1/2 archive reaches January 1996. The corresponding calendar envelope leaves 4,799 dates after the ideal feature/training allowance. Public documentation does not show whether the required XAU/USD bid and ask fields have that length or completeness.'),p('The REST API requires an entitled Tick History account; its no-additional-cost statement applies to existing clients. A trial-request form exists, but access, historical entitlements and any free export have not been confirmed. Obtain exact instrument identifiers and field-level first timestamps before considering acquisition.'),sub('Tickdatamarket: explicit XAU-USD listing, narrow margin [S03]'),p('The official spot table lists XAU-USD tick, bid/ask and minute ask/bid formats from August 1998. This is more instrument-specific than an archive-wide claim. The page also describes multi-bank/broker contributions and GMT delivery.'),p('Assuming August 1 optimistically yields 4,124 dates under the ideal screen. A later first date, holidays or missing/invalid quotes can consume the 124-date margin. The retrieved licence page exposed no usable terms. Confirm original received quotes, empty-bin policies, upstream sourcing and current delivery before paying.'),table([['Candidate','Next evidence needed'],['Olsen','Continuous gold quote inventory and present licence.'],['LSEG','Exact gold identifiers, first bid/ask dates and entitlement.'],['Tickdatamarket','Exact August start and day-level genuine-quote coverage.']],[133,358]),p('These are leads, not endorsements or acquisition approvals. No provider was contacted and no price or purchase commitment was made.','SmallX'),PageBreak()]

    story += [h('3. Public-source limits and access evidence'),sub('Dukascopy: official minute metadata is too short [S04]'),p('A direct request to the official instrument endpoint returned HTTP 200. The XAU/USD minute start decodes to 5 May 2003 at 00:01 UTC; the tick start is 00:01:03.421 UTC. That allows at most 2,904 scores before 2016 after the 400 training dates, without any quality exclusions.'),p('The daily-start field is zero and is treated as unspecified. Daily histories cannot supply intraday session RV. A separate binary history-start metadata request timed out without retry. Previous study candle probes returned 429; no price endpoint was retried in this phase.'),sub('HistData: catalogs start in 2009 [S05]'),p('Direct HTTP 200 requests to both official XAU/USD M1 and tick catalogs found 2009 as the earliest listed year. Assuming January 1 still leaves at most 1,426 scores. No archive was downloaded; undocumented older holdings are not ruled out.'),p('The official FAQ says M1 OHLC is bid based, ask appears in generic ASCII tick data, and timestamps use fixed EST without daylight-saving adjustment. Bid-only M1 bars cannot directly provide the frozen midpoint measurement.'),sub('Tick Data spot product: published envelope starts in 2008 [S06]'),p('The spot product advertises tick bid/ask history from 1 May 2008, with bid-based prebuilt M1 bars. Even that general envelope gives only 1,601 possible scores after training. Gold-specific inclusion was not established; the advertised envelope itself is insufficient.'),table([['Direct request','Result','Purpose'],['Dukascopy instruments','200; 1,040,559 bytes','Instrument start metadata'],['Dukascopy HistoryStart','ConnectTimeout','Binary start metadata only'],['HistData XAU/USD M1 catalog','200; 36,749 bytes','Available year links'],['HistData XAU/USD tick catalog','200; 33,934 bytes','Available year links']],[235,124,132]),p('Request URLs, UTC retrieval times and successful response SHA256 hashes are in METADATA_REQUESTS.json. Decoded fields and catalog years are exported separately. No candle/tick quote payload was requested. Private raw metadata snapshots are excluded from the portable/public package.','SmallX'),PageBreak()]

    story += [h('4. Long futures archives do not settle capacity'),sub('Trade start and quote start are different [S07]'),p('Tick Data lists COMEX gold futures (GC) trades from January 1984 and quotes from January 2010. The long trade history cannot be counted as equally long bid/ask midpoint history. The 2010 quote envelope leaves at most 1,165 pre-2016 scores after training.'),sub('Combined history requires a session audit [S08-S09]'),p('Portara lists combined GC intraday history from 3 September 1987 and also advertises Level 1 history from that date. Its definition says the combined stream joins newer all-session data to older pit data. Genuine historical Asian-session quotes therefore cannot be inferred from the start date. Its quote-field claim requires verification; a different vendor catalog is not an independent validation.'),p('CME notices document the December 2006 migration from after-hours ACCESS to side-by-side Globex trading. This does not prove that earlier overnight gold trading was absent. Historical session calendars and provider capture inventories must establish which windows actually existed.'),sub('A futures study would require its own design'),p('Futures change the instrument, maturity exposure, venue, trade/quote measurement and contract-roll mechanics. Roll jumps can contaminate returns and RV, while back-adjusted price levels can change log-return measurement. Freeze contract selection, roll exclusions and sampling rules before outcomes; never fill non-trading Asian hours with synthetic flat bars to meet coverage.'),sub('The power result also needs a transportability check'),p('III-C passed its designated 4,000-score simulation gates under pilot-calibrated coherent dynamics. That is a conditional simulation result. A new provider can have different quote staleness, contributor switches and dependence; a new market can differ more substantially. OANDA native-M5 equivalence does not automatically transfer to another provider.'),p('Use only the already-viewed 2016-2023 overlap to assess measurement comparability and whether the simulation assumptions remain defensible, then register any changes separately. III-C also did not demonstrate uniform null calibration across all tested sample sizes. Neither historical length nor a conditional power pass proves a fresh empirical effect.'),p('No gold-futures dataset was acquired or evaluated in this phase. The primary research target remains spot XAU/USD Asia-to-London volatility information.','SmallX'),PageBreak()]

    story += [h('5. Evidence needed before confirmation'),p('The immediate next step is a provider inventory, not an empirical model fit. A prepared request is saved in PROVIDER_REQUEST.md; it has not been sent.'),table([['Stage','Required evidence / frozen decision'],['1. Access and provenance','Exact spot-gold identifiers; first genuine bid/ask dates; contributors; readable licence and single-instrument cost.'],['2. Viewed-period bridge','2016-2023 only: timestamp/OHLC/return/RV comparability, stale quotes, smoothing, native-bar construction and gaps.'],['3. Source-specific registration','Declare period, instrument, sampling, quality, source independence, power basis and train/freeze/forecast/inference procedure.'],['4. Fresh coverage only','Bounded pre-2016 timestamp/field-presence inventory; prices quarantined; count unique eligible dates and reserve training.'],['5. Fresh confirmation','Only after registration and sufficient capacity: one evaluation under frozen rules; no opportunistic source pooling.'],['6. Final holdout','Separate later step if confirmation passes and the final protocol authorises it; remains closed here.']],[123,368]),sub('Questions ready for the providers'),p('Can you supply enough original, two-sided spot-gold quotes before 2016, plus metadata proving Asia 09:00-15:00 Tokyo and London 08:00-12:00 London coverage? What are the exact first timestamps, historical timezone/DST rules, contributor changes and quote-staleness policies? Can you first supply timestamps or genuine-bin masks without prices?'),p('Can you provide a bridge restricted to 2016-2023, without a current sample? Are bars native, smoothed, interpolated or carried forward? Are bid/ask endpoints contemporaneous? What research licence and derived-result publication rights are available?'),sub('Stop criteria and Route B'),p('If a documented candidate fails the unique-date capacity or access gate, record the reason and move to the next candidate without using forecast results to choose the feed. If no accessible qualifying source is verified after the targeted enquiries, close Route A with that scoped finding. A precision-based or smaller-effect confirmation would require a newly registered design; this report does not replace the 4,000-date gate.'),p('A fixed list of providers is not a proof of global dataset nonexistence. Access constraints and historical insufficiency are recorded separately. Budget and institutional access remain unverified; no paid access is assumed.','SmallX'),PageBreak()]

    story += [h('6. References and audit integrity'),p('Primary-provider and primary-research references checked on 06 October 2026. Full URLs, locators and candidate decisions are in evidence/SOURCES.json. Catalog dates are claims or metadata, not observed empirical score counts.','SmallX')]
    for s in sources:
        refs=s['references']
        # Limit the page to the supporting primary references; all additional API/format references remain in the evidence ledger.
        picks=refs[:2] if s['id'] in ('S01','S02','S04','S05','S08') else refs[:1]
        text=f'<b>[{s["id"]}] {escape(s["provider"])}</b> - '+ '; '.join(link(r['url'],r['title']) for r in picks)
        if s['id']=='S01':text+='; book locators: printed pp.151 and 167 (PDF pp.171 and 187).'
        story.append(p(text,'SmallX'))
    story += [sub('Local evidence and preservation'),p(f'Integrity verification matched {integrity["verified_frozen_files"]} frozen predecessor files. The verification set covers the prior III-C hash manifest plus tracked III-C files and its research bundle. It does not make a claim about every untracked/raw file in the workspace. Full filenames and hashes are in protocol/PRIOR_HASHES.json; the outcome is in results/INTEGRITY.json.'),p('Local III-C sources: results/FINAL_DECISION.json and AVAILABILITY_DECISION.json establish the existing 1,975-score capacity upper bound and no empirical evaluation. The fresh OANDA payloads remain outside this phase. Calendar counts were independently computed using actual weekday dates with Python date arithmetic.'),sub('Limitations and correct status wording'),p('No provider has supplied a fresh timestamp-only inventory in this phase. No commercial access entitlement, current single-instrument quote, licence or historical file quality is verified. General envelopes may overstate gold availability. Metadata can change, and this source search is not exhaustive.'),p('<b>Project status:</b> methodology and conditional power-design evidence have advanced; fresh empirical confirmation remains incomplete. A validated tradable strategy has not been established. Completion percentages are subjective estimates and are not reported as measured findings.'),p('Portable outputs include this report, the questionnaire, scope, source matrix, decoded metadata, request log, calendar results, audit code and file manifest. Raw snapshots, credentials and market-price datasets are excluded.','SmallX')]

    def page(canvas,doc):
        canvas.setStrokeColor(TEAL);canvas.setLineWidth(1);canvas.line(52,805,543,805)
        canvas.setFont('Helvetica',8);canvas.setFillColor(GREY)
        canvas.drawString(52,817,'XAUUSD RESEARCH  /  ROUTE A SOURCE FEASIBILITY')
        canvas.drawString(52,29,'Historical gold source audit  |  06 October 2026');canvas.drawRightString(543,29,str(doc.page))
    path=OUT/'Route_A_Historical_Gold_Source_Feasibility_Report.pdf'
    doc=SimpleDocTemplate(str(path),pagesize=A4,leftMargin=52,rightMargin=52,topMargin=54,bottomMargin=48,title='Route A: Historical Gold Source Feasibility',author='XAUUSD Research',pageCompression=1)
    doc.build(story,onFirstPage=page,onLaterPages=page)
    from pypdf import PdfReader
    reader=PdfReader(path)
    lengths=[len(x.extract_text()) for x in reader.pages]
    (ROOT/'results/REPORT_TEXT_CHECK.json').write_text(json.dumps({'pages':len(reader.pages),'characters_per_page':lengths,'all_pages_have_text':all(x>500 for x in lengths)},indent=2),encoding='utf-8')
    print(json.dumps({'pdf':str(path),'pages':len(reader.pages),'characters_per_page':lengths}))

if __name__=='__main__':main()
